min_version = "2026.7.5"

[tools]
node = "24.18.0"
go = "1.26.5"
python = "3.14.6"
bun = "1.3.14"
"aqua:pnpm/pnpm" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:starship/starship" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:fastfetch-cli/fastfetch" = "latest"
"aqua:ogulcancelik/herdr" = "latest"
"github:bugzmanov/bookokrat" = "latest"
"go:golang.org/x/tools/gopls" = { version = "latest", depends = ["go"] }
"npm:hunkdiff" = { version = "latest", depends = ["node"] }
"npm:@openai/codex" = { version = "latest", depends = ["node"] }
"npm:@vtsls/language-server" = { version = "latest", depends = ["node"] }
"npm:vscode-langservers-extracted" = { version = "latest", depends = ["node"] }
"npm:bash-language-server" = { version = "latest", depends = ["node"] }
"npm:graphql-language-service-cli" = { version = "latest", depends = ["node"] }
