---
workstation_user: hamel
workstation_home: /home/hamel
workstation_password_hash: >-
  $6$ubuntu-vagrant$x9o7n/EGM4RisioZrjkIHjwcxTMm3KZ1YnmkOLpxG4Su8TixT1egsushiNYdgyH8G6l2la43yd60D1QC.2JHh/
dotfiles_dir: "{{ workstation_home }}/Developer/dotfiles-hd"
dotfiles_repository_https: https://github.com/hd719/dotfiles-hd.git
dotfiles_repository_ssh: git@github.com:hd719/dotfiles-hd.git
nerd_font_version: 3.4.0
nerd_font_sha256: e82418895a7036158baf9a425faea7de1fe332267b218341eec44c6b5071d1ad

workstation_apt_packages:
  - acl
  - avahi-daemon
  - brave-browser
  - build-essential
  - ca-certificates
  - cloud-guest-utils
  - curl
  - docker-compose-v2
  - docker.io
  - fontconfig
  - gdm3
  - ghostscript
  - ghostty
  - git
  - imagemagick
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - lsd
  - open-vm-tools
  - open-vm-tools-desktop
  - openssh-server
  - pkg-config
  - rsync
  - sudo
  - tk-dev
  - tmux
  - ubuntu-desktop-minimal
  - unzip
  - uuid-dev
  - wl-clipboard
  - xclip
  - xz-utils
  - zlib1g-dev
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
