accent: "#f5e0dc"
details: darker
# background: "#1e1e2e"
background: "#282935"
foreground: "#efefeb"

############################################################### SEE BELOW
# background_image:
#   # the path is relative to ~/.warp/themes/default
#   # the full path to the picture is: ~/.warp/themes/warp.jpg
#   path: warp.jpg
#   # the opacity value is required and can range from 0-100
#   opacity: 10
############################################################### SEE ABOVE

terminal_colors:
  bright:
    black: "#b2b2b2"
    blue: "#68c1f9"
    cyan: "#8ff8db"
    green: "#8eedb2"
    magenta: "#eb5080"
    red: "#eb605a"
    white: "#fefefe"
    yellow: "#f8d85d"
  normal:
    black: "#1d1f20"
    blue: "#68c1f8"
    cyan: "#8ff8db"
    green: "#88fb8d"
    magenta: "#eb5181"
    red: "#eb554e"
    white: "#fefefe"
    yellow: "#f9dd6e"
