background: "#1e1e2e"
accent: "#f5e0dc"
foreground: "#cdd6f4"
details: darker
terminal_colors:
  bright:
    black: "#686868"
    blue: "#57c7ff"
    cyan: "#9aedfe"
    green: "#5af78e"
    magenta: "#ff6ac1"
    red: "#ff5c57"
    white: "#f1f1f0"
    yellow: "#f3f99d"
  normal:
    black: "#282a36"
    blue: "#57c7ff"
    cyan: "#9aedfe"
    green: "#5af78e"
    magenta: "#ff6ac1"
    red: "#ff5c57"
    white: "#f1f1f0"
    yellow: "#f3f99d"
